### ISSUE TITLE
Ajustes atividade

### ISSUE THREAD

**Issue by oliveiralex** [NatalyPG/bds04#1]
Olá Nataly, meu nome é Alexandre e estou corrigindo a sua atividade.

Seu trabalho não foi aceito, eu sinto muito! Analisando o repositório, perceba que tem apenas os pacotes dto e entities. Me pareceu que está incompleto. Desta forma, ao rodar os testes, todos falharam. 

Por gentileza, ajuste o projeto e reenvie.

Atenciosamente,
Alexandre Oliveira

**Comment by NatalyPG** [comment]
Oi Alexandre, 
eu acredito que você esteja vendo o branch master. As minhas alterações estão no main, no segundo commit. 
Obrigada!

**Comment by oliveiralex** [comment]
Ah simm, por gentileza, você pode reenviá-la para que eu corrija Nataly?
Muito obrigado!

**Comment by NatalyPG** [comment]
Enviado :) Desculpa, eu sofro para usar essas modernidades (git). Agora enviei o link direto para o main.
